name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # Your command to install dependencies, if necessary.
    - name: Build project
      run: |
        # Your command to build the project and generate the `build` folder.
    - name: Configure Git
      run: |
        git config --global user.email "HakeemYB@github.com"
        git config --global user.name "HakeemYB"
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        publish_dir: ./build
